### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Eliaskh20** [chadrs2/Self-Driving_Car_Project#1]
**Hi Dear** 
when run  DetectLaneLines.py have sume problem
**1 :** 
blur = cv2.GaussianBlur(gray_img, (5,5),0)
                                             ^
IndentationError: unindent does not match any outer indentation level

**2:**
averaged_lines=average_slope_intercept(img,lines)
                                                    ^
IndentationError: unindent does not match any outer indentation level

**thank's for help**

**Comment by chadrs2** [comment]
It should be fixed now
